"""adiciona preco m2 e m3 em cores

Revision ID: 03f44b9448d9
Revises: 9bfc3b7cb950
Create Date: 2026-01-25 17:50:24.314124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03f44b9448d9'
down_revision = '9bfc3b7cb950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cores_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preco_m2', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('preco_m3', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.drop_column('preco_unitario')
        batch_op.drop_column('unidade_medida')

    with op.batch_alter_table('historico_precos_cor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preco_m2_anterior', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('preco_m2_novo', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('preco_m3_anterior', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('preco_m3_novo', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.drop_column('preco_novo')
        batch_op.drop_column('preco_anterior')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico_precos_cor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preco_anterior', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('preco_novo', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.drop_column('preco_m3_novo')
        batch_op.drop_column('preco_m3_anterior')
        batch_op.drop_column('preco_m2_novo')
        batch_op.drop_column('preco_m2_anterior')

    with op.batch_alter_table('cores_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_medida', sa.VARCHAR(length=5), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('preco_unitario', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.drop_column('preco_m3')
        batch_op.drop_column('preco_m2')

    # ### end Alembic commands ###
