"""Adicionando percentual de desconto no colaborador

Revision ID: 064f5a82f6e5
Revises: 960de331832e
Create Date: 2026-03-02 23:33:05.185265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '064f5a82f6e5'
down_revision = '960de331832e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colaboradores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('percentual_desconto', sa.Numeric(precision=5, scale=2), nullable=True))

    with op.batch_alter_table('despesas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grupo_parcelamento', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('despesas', schema=None) as batch_op:
        batch_op.drop_column('grupo_parcelamento')

    with op.batch_alter_table('colaboradores', schema=None) as batch_op:
        batch_op.drop_column('percentual_desconto')

    # ### end Alembic commands ###
