"""Adiciona suporte a venda multipla

Revision ID: 1572d3225e42
Revises: af86326634b2
Create Date: 2026-01-15 21:33:17.011898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1572d3225e42'
down_revision = 'af86326634b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venda_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('cor_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['cor_id'], ['cores_servico.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modo', sa.String(length=20), nullable=True))
        batch_op.alter_column('descricao_servico',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('tipo_medida',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
        batch_op.alter_column('dimensao_1',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('dimensao_2',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('metragem_total',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('cor_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.alter_column('cor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('metragem_total',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('dimensao_2',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('dimensao_1',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('tipo_medida',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
        batch_op.alter_column('descricao_servico',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('modo')

    op.drop_table('venda_itens')
    # ### end Alembic commands ###
