"""Adiciona Percentual de desconto no RH

Revision ID: 1b2ab30a9860
Revises: 88f17b32c0d0
Create Date: 2026-03-01 20:01:53.207618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b2ab30a9860'
down_revision = '88f17b32c0d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colaboradores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('percentual_desconto', sa.Numeric(precision=5, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colaboradores', schema=None) as batch_op:
        batch_op.drop_column('percentual_desconto')

    # ### end Alembic commands ###
