"""Atualizacao completa estoque e vendas

Revision ID: 2296eae85c22
Revises: 8e3d0bba1697
Create Date: 2026-02-16 15:14:59.958205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2296eae85c22'
down_revision = '8e3d0bba1697'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Ajustes em movimentacoes_estoque
    with op.batch_alter_table('movimentacoes_estoque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_movimentacao', sa.DateTime(), nullable=True))
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('origem',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_column('data')

    # 2. Ajustes em produtos_estoque (DIVIDIDO EM 3 PASSOS)
    
    # Passo A: Adicionar coluna permitindo NULL
    with op.batch_alter_table('produtos_estoque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantidade_minima', sa.Numeric(precision=10, scale=3), nullable=True))
        # AQUI MUDOU: nullable=True
        batch_op.add_column(sa.Column('valor_unitario', sa.Numeric(10, 2), nullable=True)) 
        batch_op.add_column(sa.Column('consumo_por_m2', sa.Numeric(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('consumo_por_m3', sa.Numeric(precision=10, scale=4), nullable=True))
        
        batch_op.alter_column('unidade',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=5),
               existing_nullable=True)
        
        batch_op.drop_column('estoque_minimo')
        batch_op.drop_column('preco_m3')
        batch_op.drop_column('preco_m2')

    # Passo B: Preencher valores nulos com 0.00
    op.execute("UPDATE produtos_estoque SET valor_unitario = 0.00 WHERE valor_unitario IS NULL")

    # Passo C: Tornar a coluna obrigatória (NOT NULL)
    with op.batch_alter_table('produtos_estoque', schema=None) as batch_op:
        batch_op.alter_column('valor_unitario', nullable=False, existing_type=sa.Numeric(10, 2))

    # 3. Ajustes em venda_itens
    with op.batch_alter_table('venda_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metragem_total', sa.Numeric(precision=10, scale=3), nullable=True))
        batch_op.add_column(sa.Column('tipo_medida', sa.String(length=5), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda_itens', schema=None) as batch_op:
        batch_op.drop_column('tipo_medida')
        batch_op.drop_column('metragem_total')

    with op.batch_alter_table('produtos_estoque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preco_m2', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('preco_m3', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('estoque_minimo', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True))
        batch_op.alter_column('unidade',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.drop_column('consumo_por_m3')
        batch_op.drop_column('consumo_por_m2')
        batch_op.drop_column('valor_unitario')
        batch_op.drop_column('quantidade_minima')

    with op.batch_alter_table('movimentacoes_estoque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('origem',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('data_movimentacao')
    # ### end Alembic commands ###