"""Adiciona rastreabilidade completa em vendas

Revision ID: 2984bf2309e5
Revises: 42223d24428e
Create Date: 2026-01-14 22:01:56.190040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2984bf2309e5'
down_revision = '42223d24428e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_inicio_producao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('usuario_producao_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('data_pronto', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('usuario_pronto_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('data_entrega', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('usuario_entrega_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_pronto_id'], ['id'])
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_entrega_id'], ['id'])
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_producao_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('usuario_entrega_id')
        batch_op.drop_column('data_entrega')
        batch_op.drop_column('usuario_pronto_id')
        batch_op.drop_column('data_pronto')
        batch_op.drop_column('usuario_producao_id')
        batch_op.drop_column('data_inicio_producao')

    # ### end Alembic commands ###
