"""Cria tabelas de metas mensais e vendedores

Revision ID: 2ac0af862d1d
Revises: 507a35c6f944
Create Date: 2026-01-18 13:35:08.193326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ac0af862d1d'
down_revision = '507a35c6f944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metas_mensais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('valor_loja', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('dias_uteis', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metas_vendedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meta_mensal_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('valor_meta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['meta_mensal_id'], ['metas_mensais.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metas_vendedores')
    op.drop_table('metas_mensais')
    # ### end Alembic commands ###
