"""Adiciona tabela documentos usuarios

Revision ID: 2ec9cf1e58e5
Revises: 03f44b9448d9
Create Date: 2026-01-27 19:25:01.031494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec9cf1e58e5'
down_revision = '03f44b9448d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('nome_original', sa.String(length=255), nullable=False),
    sa.Column('tipo_arquivo', sa.String(length=10), nullable=True),
    sa.Column('tamanho_kb', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('enviado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['enviado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documentos_usuarios')
    # ### end Alembic commands ###
