"""Ajuste nome coluna email

Revision ID: 34e38f1f06d6
Revises: 
Create Date: 2026-02-08 18:58:22.512205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34e38f1f06d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.drop_constraint(batch_op.f('usuarios_email_recuperacao_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('email_recuperacao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_recuperacao', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('usuarios_email_recuperacao_key'), ['email_recuperacao'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('email')

    # ### end Alembic commands ###
