"""Add faz_parte_meta colaborador

Revision ID: 3611279c58de
Revises: 550e675c06ac
Create Date: 2026-02-18 13:17:38.831419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3611279c58de'
down_revision = '550e675c06ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colaboradores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faz_parte_meta', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colaboradores', schema=None) as batch_op:
        batch_op.drop_column('faz_parte_meta')

    # ### end Alembic commands ###
