"""Adiciona configuracao de dias da semana e feriados em metas

Revision ID: 4deadf804b3f
Revises: 2ac0af862d1d
Create Date: 2026-01-18 13:49:17.114449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4deadf804b3f'
down_revision = '2ac0af862d1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metas_mensais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config_semana', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('config_feriados', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metas_mensais', schema=None) as batch_op:
        batch_op.drop_column('config_feriados')
        batch_op.drop_column('config_semana')

    # ### end Alembic commands ###
