"""Adiciona acrescimo na venda

Revision ID: 54aae6ea0ac4
Revises: b30080719a86
Create Date: 2026-01-13 22:39:29.457176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54aae6ea0ac4'
down_revision = 'b30080719a86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_acrescimo', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.drop_column('valor_acrescimo')

    # ### end Alembic commands ###
