"""Removendo custo unitario

Revision ID: 550e675c06ac
Revises: 2296eae85c22
Create Date: 2026-02-16 15:54:45.277086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550e675c06ac'
down_revision = '2296eae85c22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos_estoque', schema=None) as batch_op:
        batch_op.alter_column('unidade',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.drop_column('valor_unitario')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos_estoque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_unitario', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.alter_column('unidade',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)

    # ### end Alembic commands ###
