"""Adiciona precos m2 e m3 no estoque

Revision ID: 5bd1b94ef392
Revises: 94820d34d9b4
Create Date: 2026-01-27 20:44:30.540849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd1b94ef392'
down_revision = '94820d34d9b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos_estoque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preco_m2', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('preco_m3', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos_estoque', schema=None) as batch_op:
        batch_op.drop_column('preco_m3')
        batch_op.drop_column('preco_m2')

    # ### end Alembic commands ###
