"""Adiciona coluna equipe em usuarios

Revision ID: 5d5b23214807
Revises: 4deadf804b3f
Create Date: 2026-01-18 15:33:48.778164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d5b23214807'
down_revision = '4deadf804b3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipe', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('equipe')

    # ### end Alembic commands ###
