"""Fotos para banco de dados

Revision ID: 88f17b32c0d0
Revises: e433e0845168
Create Date: 2026-02-18 15:01:24.659137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88f17b32c0d0'
down_revision = 'e433e0845168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fotos_itens_venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_arquivo', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('tipo_mime', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('dados_binarios', sa.LargeBinary(), nullable=False))
        batch_op.drop_column('caminho_arquivo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fotos_itens_venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caminho_arquivo', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('dados_binarios')
        batch_op.drop_column('tipo_mime')
        batch_op.drop_column('nome_arquivo')

    # ### end Alembic commands ###
