"""Adicionando campos financeiros ao colaborador

Revision ID: 8e3d0bba1697
Revises: a84a93026bd9
Create Date: 2026-02-16 12:54:09.225105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e3d0bba1697'
down_revision = 'a84a93026bd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colaboradores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chave_pix', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('banco', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('agencia', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('conta', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('frequencia_pagamento', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('dia_pagamento', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colaboradores', schema=None) as batch_op:
        batch_op.drop_column('dia_pagamento')
        batch_op.drop_column('frequencia_pagamento')
        batch_op.drop_column('conta')
        batch_op.drop_column('agencia')
        batch_op.drop_column('banco')
        batch_op.drop_column('chave_pix')

    # ### end Alembic commands ###
