"""Adiciona historico de itens

Revision ID: 919db58bfb56
Revises: ab63f115632f
Create Date: 2026-01-17 21:58:00.107608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '919db58bfb56'
down_revision = 'ab63f115632f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_venda_historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('status_anterior', sa.String(length=20), nullable=False),
    sa.Column('status_novo', sa.String(length=20), nullable=False),
    sa.Column('acao', sa.String(length=50), nullable=True),
    sa.Column('data_acao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['venda_itens.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_venda_historico')
    # ### end Alembic commands ###
