"""Cria tabelas de estoque

Revision ID: 94820d34d9b4
Revises: 2ec9cf1e58e5
Create Date: 2026-01-27 20:04:42.383596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94820d34d9b4'
down_revision = '2ec9cf1e58e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('unidade', sa.String(length=10), nullable=True),
    sa.Column('quantidade_atual', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('estoque_minimo', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimentacoes_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('saldo_anterior', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('saldo_novo', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('origem', sa.String(length=20), nullable=True),
    sa.Column('referencia_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('observacao', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos_estoque.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimentacoes_estoque')
    op.drop_table('produtos_estoque')
    # ### end Alembic commands ###
