"""Add grupo_parcelamento em despesas

Revision ID: 960de331832e
Revises: 1b2ab30a9860
Create Date: 2026-03-01 21:49:51.795319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960de331832e'
down_revision = '1b2ab30a9860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('despesas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grupo_parcelamento', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('despesas', schema=None) as batch_op:
        batch_op.drop_column('grupo_parcelamento')

    # ### end Alembic commands ###
