"""Aumenta precisao das metas para Numeric(15,2)

Revision ID: 9bfc3b7cb950
Revises: 5d5b23214807
Create Date: 2026-01-18 16:27:19.559011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bfc3b7cb950'
down_revision = '5d5b23214807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metas_mensais', schema=None) as batch_op:
        batch_op.alter_column('valor_loja',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metas_mensais', schema=None) as batch_op:
        batch_op.alter_column('valor_loja',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###
