"""Adiciona Modulo Vendas

Revision ID: a0cb96e66ac2
Revises: 91e5410ef8a5
Create Date: 2026-01-13 21:58:17.605023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0cb96e66ac2'
down_revision = '91e5410ef8a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cores_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('unidade_medida', sa.String(length=5), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_precos_cor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cor_id', sa.Integer(), nullable=False),
    sa.Column('preco_anterior', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_novo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cor_id'], ['cores_servico.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_cliente', sa.String(length=2), nullable=False),
    sa.Column('cliente_nome', sa.String(length=150), nullable=False),
    sa.Column('cliente_contato', sa.String(length=50), nullable=False),
    sa.Column('cliente_documento', sa.String(length=20), nullable=True),
    sa.Column('descricao_servico', sa.Text(), nullable=False),
    sa.Column('observacoes_internas', sa.Text(), nullable=True),
    sa.Column('tipo_medida', sa.String(length=5), nullable=False),
    sa.Column('dimensao_1', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('dimensao_2', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('dimensao_3', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('metragem_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantidade_pecas', sa.Integer(), nullable=True),
    sa.Column('cor_id', sa.Integer(), nullable=False),
    sa.Column('cor_nome_snapshot', sa.String(length=100), nullable=True),
    sa.Column('preco_unitario_snapshot', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_base', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tipo_desconto', sa.String(length=10), nullable=True),
    sa.Column('valor_desconto_aplicado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_final', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cor_id'], ['cores_servico.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendas')
    op.drop_table('historico_precos_cor')
    op.drop_table('cores_servico')
    # ### end Alembic commands ###
