"""Add Porcentagem Adiantamento

Revision ID: a84a93026bd9
Revises: f02399b3e5c6
Create Date: 2026-02-16 12:08:41.244536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a84a93026bd9'
down_revision = 'f02399b3e5c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colaboradores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('percentual_adiantamento', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colaboradores', schema=None) as batch_op:
        batch_op.drop_column('percentual_adiantamento')

    # ### end Alembic commands ###
