"""Adiciona usuarios nos itens

Revision ID: ab63f115632f
Revises: de0bcac25150
Create Date: 2026-01-15 23:19:15.902085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab63f115632f'
down_revision = 'de0bcac25150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_producao_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('usuario_pronto_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('usuario_entrega_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_entrega_id'], ['id'])
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_producao_id'], ['id'])
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_pronto_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda_itens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('usuario_entrega_id')
        batch_op.drop_column('usuario_pronto_id')
        batch_op.drop_column('usuario_producao_id')

    # ### end Alembic commands ###
