"""Adiciona produto_id em vendas e itens

Revision ID: af51f9fa2d61
Revises: 5bd1b94ef392
Create Date: 2026-01-27 21:38:25.315813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af51f9fa2d61'
down_revision = '5bd1b94ef392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('produto_id', sa.Integer(), nullable=True))
        batch_op.alter_column('cor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'produtos_estoque', ['produto_id'], ['id'])

    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('produto_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'produtos_estoque', ['produto_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('produto_id')

    with op.batch_alter_table('venda_itens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('cor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('produto_id')

    # ### end Alembic commands ###
