"""Adiciona cancelamento e auditoria

Revision ID: af86326634b2
Revises: 2984bf2309e5
Create Date: 2026-01-14 22:26:50.319991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af86326634b2'
down_revision = '2984bf2309e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivo_cancelamento', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('data_cancelamento', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('usuario_cancelamento_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_cancelamento_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('usuario_cancelamento_id')
        batch_op.drop_column('data_cancelamento')
        batch_op.drop_column('motivo_cancelamento')

    # ### end Alembic commands ###
