"""Adiciona dados de RH e inverte hierarquia

Revision ID: bd10ea37c7bf
Revises: 7c0b937859a2
Create Date: 2026-01-12 22:54:16.787724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd10ea37c7bf'
down_revision = '7c0b937859a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.String(length=14), nullable=True))
        batch_op.add_column(sa.Column('telefone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('salario', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.create_unique_constraint(None, ['cpf'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('salario')
        batch_op.drop_column('telefone')
        batch_op.drop_column('cpf')

    # ### end Alembic commands ###
