"""Adiciona dados binarios em documentos

Revision ID: c3b483f26a73
Revises: af51f9fa2d61
Create Date: 2026-01-28 21:59:42.780059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3b483f26a73'
down_revision = 'af51f9fa2d61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dados_binarios', sa.LargeBinary(), nullable=True))
        batch_op.alter_column('tipo_arquivo',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('tamanho_kb',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('nome_arquivo',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_usuarios', schema=None) as batch_op:
        batch_op.alter_column('nome_arquivo',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('tamanho_kb',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('tipo_arquivo',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.drop_column('dados_binarios')

    # ### end Alembic commands ###
