"""Tabelas Corporativo e RH

Revision ID: c522776da1a6
Revises: 34e38f1f06d6
Create Date: 2026-02-16 09:56:15.753307

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c522776da1a6'
down_revision = '34e38f1f06d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documentos_usuarios')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos_usuarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome_original', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('tipo_arquivo', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('tamanho_kb', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('nome_arquivo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('dados_binarios', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('criado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('enviado_por_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['enviado_por_id'], ['usuarios.id'], name=op.f('documentos_usuarios_enviado_por_id_fkey')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('documentos_usuarios_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('documentos_usuarios_pkey'))
    )
    # ### end Alembic commands ###
