"""Adiciona status nos itens

Revision ID: de0bcac25150
Revises: 1572d3225e42
Create Date: 2026-01-15 22:15:02.688782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de0bcac25150'
down_revision = '1572d3225e42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('data_inicio_producao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('data_pronto', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('data_entregue', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda_itens', schema=None) as batch_op:
        batch_op.drop_column('data_entregue')
        batch_op.drop_column('data_pronto')
        batch_op.drop_column('data_inicio_producao')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
