"""Add acrescimo e desconto em Despesa

Revision ID: e2cdb495a034
Revises: 064f5a82f6e5
Create Date: 2026-05-31 21:33:16.429307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2cdb495a034'
down_revision = '064f5a82f6e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('despesas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_acrescimo', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('valor_desconto', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('motivo_ajuste', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('despesas', schema=None) as batch_op:
        batch_op.drop_column('motivo_ajuste')
        batch_op.drop_column('valor_desconto')
        batch_op.drop_column('valor_acrescimo')

    # ### end Alembic commands ###
