"""Atualizacao RH Financeiro

Revision ID: f02399b3e5c6
Revises: c522776da1a6
Create Date: 2026-02-16 11:57:06.127542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f02399b3e5c6'
down_revision = 'c522776da1a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('despesas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colaborador_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('origem', sa.String(length=30), nullable=True))
        batch_op.create_foreign_key(None, 'colaboradores', ['colaborador_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('despesas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('origem')
        batch_op.drop_column('colaborador_id')

    # ### end Alembic commands ###
